apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: staging
  labels:
    app: flask-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      # PERBAIKAN: Disable automounting service account token untuk Hardening
      automountServiceAccountToken: false
      containers:
      - name: flask-app
        # PERBAIKAN: Menggunakan placeholder IMAGE_TAG agar tidak hardcoded 'latest'
        image: kikyputraa/sast-scan-test:IMAGE_TAG
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        # PERBAIKAN: Menambahkan Resource Requests & Limits serta Storage
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"
            ephemeral-storage: "200Mi"