name: DevSecOps Pipeline

on:
  push:
    branches: [ "staging", "main" ]

jobs:
  sast_bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bandit Scan
        run: |
          pip install bandit
          bandit -r app/

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pytest with Coverage
        run: |
          pip install pytest pytest-cov Flask
          pytest --cov=app --cov-report=xml tests/
      - name: Upload Coverage for Sonar
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: coverage.xml

  sonarqube_check:
    needs: [unit_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifact
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_job:
    needs: [sonarqube_check, sast_bandit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Save Image
        run: |
          docker build -t kikyputraa/sast-scan-test:${{ github.sha }} .
          docker save kikyputraa/sast-scan-test:${{ github.sha }} > app_image.tar
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: app_image.tar

  security_check:
    needs: [build_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Image
        uses: actions/download-artifact@v4
        with:
          name: app-image
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          input: 'app_image.tar'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'
          pkg-types: 'library'

  push_job:
    needs: [security_check]
    runs-on: ubuntu-latest
    steps:
      - name: Download Image
        uses: actions/download-artifact@v4
        with:
          name: app-image
      - name: Login and Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker load < app_image.tar
          docker push kikyputraa/sast-scan-test:${{ github.sha }}
          docker tag kikyputraa/sast-scan-test:${{ github.sha }} kikyputraa/sast-scan-test:latest
          docker push kikyputraa/sast-scan-test:latest

  deploy_job:
    needs: [push_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Manifest Update
        run: |
          [[ "${{ github.ref }}" == "refs/heads/main" ]] && (NSP="default"; PT="30001") || (NSP="staging"; PT="30002")
          sed -i "s|namespace:.*|namespace: $NSP|g" k8s/deployment.yaml
          sed -i "s|nodePort:.*|nodePort: $PT|g" k8s/service.yaml
          sed -i "s|image:.*|image: kikyputraa/sast-scan-test:${{ github.sha }}|g" k8s/deployment.yaml