name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  sast:
    name: Security Scan (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Penting untuk SonarCloud agar bisa melihat history git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Bandit (Security Audit)
        run: |
          pip install bandit
          # Flag -r: recursive, -ll: level LOW atau lebih tinggi
          # Flag -x: abaikan folder test jika ada
          bandit -r app/ -ll -v
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.qualitygate.wait=true

  build-and-scan:
    name: Build and Image Scan
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/flask-app:${{ github.sha }} .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USER }}/flask-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # MEMBUAT PIPELINE GAGAL jika ditemukan celah
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/flask-app:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    needs: build-and-scan
    runs-on: self-hosted # Menggunakan runner lokal Anda (WSL2)
    steps:
      - uses: actions/checkout@v4

      - name: Set Environment Context
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "NAMESPACE=default" >> $GITHUB_ENV
            echo "NODE_PORT=30001" >> $GITHUB_ENV
          else
            echo "NAMESPACE=staging" >> $GITHUB_ENV
            echo "NODE_PORT=30002" >> $GITHUB_ENV
          fi

      - name: Deploy to Minikube
        run: |
          sed -i "s|{{IMAGE_TAG}}|${{ github.sha }}|g" k8s/deployment.yaml
          sed -i "s|{{NAMESPACE}}|${{ env.NAMESPACE }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml -n ${{ env.NAMESPACE }}