name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "staging" ]

jobs:
  sast_bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install bandit && bandit -r app/ -ll

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          pip install pytest pytest-cov Flask
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=app --cov-report=xml:coverage.xml tests/
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonarqube_check:
    needs: [sast_bandit, unit_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_image:
    needs: [sonarqube_check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Save
        run: |
          docker build -t kikyputraa/devops-playground:${{ github.sha }} .
          docker save kikyputraa/devops-playground:${{ github.sha }} > app_image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: docker-artifact
          path: app_image.tar

  container_security:
    needs: [build_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-artifact
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          input: 'app_image.tar'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true # Melewati celah yang belum ada solusinya
          vuln-type: 'os,library'

  push_image:
    needs: [container_security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-artifact
      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker load < app_image.tar
          docker push kikyputraa/devops-playground:${{ github.sha }}
          docker tag kikyputraa/devops-playground:${{ github.sha }} kikyputraa/devops-playground:latest
          docker push kikyputraa/devops-playground:latest

  deploy:
    needs: [push_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          [[ "${{ github.ref }}" == "refs/heads/main" ]] && (NSP="default"; PT="30001") || (NSP="staging"; PT="30002")
          sed -i "s|namespace:.*|namespace: $NSP|g" k8s/deployment.yaml
          sed -i "s|nodePort:.*|nodePort: $PT|g" k8s/service.yaml
          sed -i "s|image:.*|image: kikyputraa/devops-playground:${{ github.sha }}|g" k8s/deployment.yaml